### PR TITLE
avoid date classes not getting respected by stopifnot, fixes #213

### LINKED ISSUE #213: regularize date function only respects first possible argument
because class(x)[1] "Date" class is not respected, if it's not POSIXct – it's not working. 

```r
Error in regularize_date(x$time) : 
  class(x)[1] %in% c("POSIXct", "Date") is not TRUE

```

This causes problems when using the popular fread function from data.table because they return c("IDate","Date") none of which is POSIXct. I believe one should definitely use inherits here instead of class.

 Fill provide PR fix.

### PR DESCRIPTION
**Pull request by mbannert**
## Description
regularize date helpers used ONLY the first element of the vectore returned by class. Hence if a Date had multiple classes like many advanced date objects have, stopifnot caused an error. data.table adds *iDate* on top of a standard date class while preserving the standard Date class. Because *Date* is only the second element of the class vector, it's not respected, *iDate* is not known and the function crashes despite the fact that the input is a perfectly fine date. 

## Related Issue

fix #213  

## Example

see diff, it's only a small change and the diffs shows exactly what happens.

### CODE REVIEW

File: R/date_helpers.R [hunk 1]
```diff
@@ -24,7 +24,7 @@ as_time_or_date <- function(x) {
 #' @param x Date or POSIXct
 #' @noRd
 regularize_date <- function(x) {
-  stopifnot(class(x)[1] %in% c("POSIXct", "Date"))
+  stopifnot(inherits(x,c("POSIXct", "Date")))
```
Comment (christophsax) [inline R/date_helpers.R:27]: Nice! I wasn't aware that `inherits()` can have multiple classes. 

Can you follow the style guide and add a space after `x`?

**Review by christophsax — CHANGES_REQUESTED** [review]

**Comment by mbannert** [comment]
I guess you mean a space after the comma. Did that, hope it's fine now. .

**Review by christophsax — APPROVED** [review]
